import React from "react";
export const CalendarIcon = () => <span aria-hidden>📅</span>;
export const Check = () => <span aria-hidden>✔</span>;
export const ChevronDown = ({ open }) => <span aria-hidden>{open ? "▴" : "▾"}</span>;
export const ListPlus = () => <span aria-hidden>＋</span>;
export const Pencil = () => <span aria-hidden>✎</span>;
export const Plus = () => <span aria-hidden>＋</span>;
export const Save = () => <span aria-hidden>💾</span>;
export const Trash2 = () => <span aria-hidden>🗑</span>;
export const X = () => <span aria-hidden>×</span>;
